version: '3'

services:
  zerolog-golang-app:
    build:
      dockerfile: Dockerfile
    container_name: zerolog-golang-app
    volumes:
      - ./logs:/src/logs
    ports:
      - "8080:8080"

  golang-app-filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    container_name: golang-app-filebeat
    command: filebeat -e -strict.perms=false
    volumes:
      - ./logs:/src/logs
    env_file:
      - .env